name: SkyWars
version: 1.0.2
api: 1.8.0

main: sw\skywars\SkyWarsPlugIn
author: redstonealmeida
description: SkyWars mini-game
commands:
 skw:
  description: "SkyWars mini-game"
  permission: skyw.plugin.skywars
permissions:
 skyw.plugin.skywars:
  description: "skyw.plugin.skywars"
  default: op
